version: '3.8'

services:
  mailserver:
    image: analogic/poste.io
    container_name: mailserver
    hostname: ${POSTEO_HOST_NAME}
    environment:
      - TZ=${TZ}
      - POSTEO_DOMAIN=${POSTEO_DOMAIN}
      - POSTEO_ADMIN_PASSWORD=${POSTEO_ADMIN_PASSWORD}
      - POSTEO_POSTMASTER_PASSWORD=${POSTEO_POSTMASTER_PASSWORD}
      - POSTEO_SMTP_PORT=25
      - POSTEO_IMAP_PORT=143
      - POSTEO_WEBSERVER_PORT=80
      - POSTEO_HTTP_PORT=80
    volumes:
    - ./data:/data
    - ./mail:/mail
    - ./certs:/etc/ssl/certs  # Add this for SSL certificates
    ports:
      - "25:25"      # SMTP
      - "143:143"    # IMAP
      - "88:80"      # Web interface (non-SSL)
      - "8443:443"    # Web interface (SSL, optional)
    restart: unless-stopped